import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CircleMarker, MapContainer, Popup, TileLayer, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import './styles.css';
import { getActionPlan, getDashboardSummary, getHealth, getInterventions, getLocation, getLocations, getModelMetrics, getPrediction, simulateInterventions, uploadData } from './services/api.ts';

const pages = [['overview', 'Overview'], ['map', 'Risk Map'], ['intelligence', 'Road Intelligence'], ['prediction', 'Prediction'], ['interventions', 'Interventions'], ['simulator', 'What-if Simulator'], ['action', 'Priority Action Plan'], ['upload', 'Data Upload'], ['model', 'Model Insights']];
const riskColor = { Low: '#9be564', Medium: '#f2c94c', High: '#ff9c5c', Critical: '#ef6a6a' };
const fmt = (value, digits = 1) => typeof value === 'number' ? value.toFixed(digits) : value ?? '—';

function Bars({ items = [], color = '#c9f277' }) {
  const max = Math.max(...items.map((item) => item.value || item.accidents || 0), 1);
  return <div className="chart-bars">{items.map((item) => <div className="chart-bar" key={item.name || item.cause || item.hour || item.year}><span>{item.name || item.cause || item.hour || item.year}</span><i><em style={{ width: `${Math.max(3, ((item.value || item.accidents || 0) / max) * 100)}%`, background: color }} /></i><b>{item.value ?? item.accidents}</b></div>)}</div>;
}
function RiskBadge({ level, score }) { return <span className="risk-badge" style={{ color: riskColor[level] || '#c9f277' }}>{level}<strong>{score}</strong></span>; }
function MapCenter({ location }) { const map = useMap(); useEffect(() => { if (location) map.setView([location.latitude, location.longitude], 12); }, [location, map]); return null; }

function Overview({ summary, locations, select, open }) {
  const top = summary?.highest_risk_location;
  const topIntervention = top?.risk_level === 'Critical' ? 'Resurface and improve lane markings' : 'Targeted road safety audit';
  return <div className="page-stack"><section className="hero"><div><p className="eyebrow">AUTHORITY OVERVIEW / {summary?.data_label}</p><h2>Make the next road safety action count.</h2><p>Historical accident patterns become explainable priorities for Indian road corridors.</p></div><div className="hero-stat"><strong>{summary?.average_risk_score ?? '—'}</strong><span>average risk / 100</span></div></section><section className="kpis">{[['ACCIDENTS', summary?.total_accidents], ['FATALITIES', summary?.total_fatalities], ['INJURIES', summary?.total_injuries], ['CRITICAL ROADS', summary?.critical_risk_roads], ['HIGH RISK ROADS', summary?.high_risk_roads], ['PEAK HOUR', summary?.peak_risk_hour != null ? `${String(summary.peak_risk_hour).padStart(2, '0')}:00` : '—']].map(([label, value]) => <div className="kpi" key={label}><span>{label}</span><strong>{value ?? '—'}</strong></div>)}</section><div className="overview-grid"><section className="panel"><div className="panel-head"><div><p className="eyebrow">RISK DISTRIBUTION</p><h3>Corridor exposure</h3></div><span className="count">{locations.length} locations</span></div><div className="distribution">{Object.entries(summary?.risk_distribution || {}).map(([level, value]) => <div key={level}><i style={{ background: riskColor[level] }} /><b>{value}</b><span>{level}</span></div>)}</div><p className="eyebrow section-label">ACCIDENT TREND</p><Bars items={(summary?.trend || []).map((item) => ({ name: item.year, value: item.accidents }))} /></section><section className="panel decision"><p className="eyebrow">DECISION SUMMARY</p><h3>Recommended authority action</h3><div className="decision-score"><strong>{top?.risk_score ?? '—'}</strong><span>{top?.risk_level || '—'} risk<br />highest-risk corridor</span></div><dl><div><dt>Corridor</dt><dd>{top?.road_name || '—'}</dd></div><div><dt>Primary driver</dt><dd>{top ? 'Road conditions and severity' : '—'}</dd></div><div><dt>Vulnerable group</dt><dd>{summary?.most_vulnerable_user || '—'}</dd></div><div><dt>Recommended first action</dt><dd>{topIntervention}</dd></div></dl><button className="action" onClick={() => top && open(top.id)}>Analyze corridor →</button></section></div><div className="overview-grid"><section className="panel"><div className="panel-head"><div><p className="eyebrow">TOP RISK ROADS</p><h3>Where attention is needed</h3></div></div>{locations.slice(0, 5).map((item) => <button className="rank-row" key={item.id} onClick={() => open(item.id)}><span><b>{item.road_name}</b><small>{item.state} / {item.district}</small></span><RiskBadge level={item.risk_level} score={item.risk_score} /></button>)}</section><section className="panel"><p className="eyebrow">CAUSE SIGNALS</p><h3>What is driving incidents?</h3><Bars items={summary?.top_causes || []} color="#ff9c5c" /><p className="eyebrow section-label">VULNERABLE USERS</p><Bars items={summary?.vulnerable_users || []} color="#c9f277" /></section></div></div>;
}

function RiskMap({ locations, select, open }) {
  const [filters, setFilters] = useState({ state: '', risk: '' });
  const states = [...new Set(locations.map((item) => item.state))].sort();
  const filtered = locations.filter((item) => (!filters.state || item.state === filters.state) && (!filters.risk || item.risk_level === filters.risk));
  const hasCoordinates = filtered.some((item) => Number.isFinite(item.latitude) && Number.isFinite(item.longitude));
  return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">{hasCoordinates ? 'GEOSPATIAL RISK VIEW' : 'STATE / UT RISK VIEW'}</p><h2>{hasCoordinates ? 'Risk Map' : 'Region Risk Ranking'}</h2><p>{hasCoordinates ? 'Live markers from the RoadPulse API.' : 'The official source has no coordinates; showing a ranked geographic table.'}</p></div><div className="filter-row"><select value={filters.state} onChange={(event) => setFilters({ ...filters, state: event.target.value })}><option value="">All states</option>{states.map((state) => <option key={state}>{state}</option>)}</select><select value={filters.risk} onChange={(event) => setFilters({ ...filters, risk: event.target.value })}><option value="">All risk levels</option>{['Critical', 'High', 'Medium', 'Low'].map((level) => <option key={level}>{level}</option>)}</select></div></div><section className="panel map-frame">{hasCoordinates ? <MapContainer center={[20.5937, 78.9629]} zoom={5} scrollWheelZoom className="leaflet-map"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><MapCenter location={filtered[0]} />{filtered.filter((item) => Number.isFinite(item.latitude) && Number.isFinite(item.longitude)).map((item) => <CircleMarker key={item.id} center={[item.latitude, item.longitude]} radius={Math.max(8, Math.min(16, item.risk_score / 6))} pathOptions={{ color: riskColor[item.risk_level], fillColor: riskColor[item.risk_level], fillOpacity: .82 }} eventHandlers={{ click: () => select(item.id) }}><Popup><b>{item.road_name}</b><br />{item.district}, {item.state}<br /><strong>{item.risk_score} / 100 · {item.risk_level}</strong><br />{item.accidents} accidents · {item.fatalities} fatalities<br /><button className="popup-action" onClick={() => open(item.id)}>Analyze road</button></Popup></CircleMarker>)}</MapContainer> : <div className="region-table">{filtered.map((item) => <button className="rank-row" key={item.id} onClick={() => open(item.id)}><span><b>{item.state}</b><small>{item.year} · {item.accidents ?? '—'} accidents</small></span><RiskBadge level={item.risk_level} score={item.risk_score} /></button>)}</div>}<div className="map-legend">{Object.entries(riskColor).map(([level, color]) => <span key={level}><i style={{ background: color }} />{level}</span>)}</div></section><section className="panel compact-table"><div className="panel-head"><h3>Filtered regions</h3><span className="count">{filtered.length} results</span></div>{filtered.slice(0, 8).map((item) => <button className="rank-row" key={item.id} onClick={() => open(item.id)}><span><b>{item.road_name}</b><small>{item.state} / {item.district || 'State/UT'}</small></span><RiskBadge level={item.risk_level} score={item.risk_score} /></button>)}</section></div>;
}

function Intelligence({ detail, prediction, openSimulator }) {
  if (!detail) return <Empty text="Select a corridor from Risk Map." />;
  const official = detail.state && !detail.road_segment;
  return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">{official ? 'STATE ROAD SAFETY INTELLIGENCE' : 'ROAD INTELLIGENCE'}</p><h2>{official ? detail.state : detail.road_name}</h2><p>{official ? `State/UT · ${detail.year}` : `${detail.state} / ${detail.district} · ${detail.road_segment}`}</p></div><RiskBadge level={detail.risk.risk_level} score={detail.risk.risk_score} /></div><div className="facts facts-large"><div><span>CURRENT RISK</span><b>{detail.risk.risk_score} / 100</b></div><div><span>PREDICTED RISK</span><b>{prediction?.predicted_risk ?? '—'}</b></div><div><span>TREND</span><b>{prediction?.trend || '—'}</b></div><div><span>{official ? 'HIGHEST RISK YEAR' : 'PEAK HOUR'}</span><b>{official ? detail.year : `${String(detail.peak_hour).padStart(2, '0')}:00`}</b></div></div><div className="overview-grid"><section className="panel"><p className="eyebrow">WHY IS THIS LOCATION RISKY?</p><h3>Contribution signals</h3><p className="explanation">{detail.explanation}</p>{detail.risk.contribution_breakdown.map((factor) => <div className="bar-row" key={factor.name}><div><span>{factor.name}</span><b>{factor.score}</b></div><i><em style={{ width: `${Math.min(100, factor.score / factor.max_score * 100)}%` }} /></i></div>)}</section><section className="panel"><p className="eyebrow">{official ? 'CAUSE ANALYSIS' : 'CAUSE ANALYSIS'}</p><h3>{official && !detail.causes.length ? 'Not available in source' : 'Incident drivers'}</h3>{detail.causes.length ? <Bars items={detail.causes.map((item) => ({ name: item.cause, value: item.accidents }))} color="#ff9c5c" /> : <p className="explanation">The loaded official State/UT files do not include cause categories.</p>}<p className="eyebrow section-label">VULNERABLE USERS</p>{detail.vulnerability.length ? <Bars items={detail.vulnerability.map((item) => ({ name: item.user, value: item.accidents }))} /> : <p className="explanation">The loaded official State/UT files do not include road-user categories.</p>}</section></div><div className="overview-grid"><section className="panel"><p className="eyebrow">{official ? 'ANNUAL TREND' : 'WHEN IS RISK HIGHEST?'}</p><h3>{official ? 'Yearly accident trend' : 'Hourly pattern'}</h3>{official ? <Bars items={detail.trend.map((item) => ({ name: item.year, value: item.accidents }))} color="#f2c94c" /> : <Bars items={detail.temporal.map((item) => ({ name: `${item.hour}:00`, value: item.accidents }))} color="#f2c94c" />}</section><section className="panel"><p className="eyebrow">PLANNING ACTION</p><h3>Recommended Authority Action</h3><p className="explanation">Use official accident burden to prioritize this {official ? 'State/UT' : 'road'}; scenario assumptions are separated from observed data.</p><button className="action" onClick={openSimulator}>Open what-if simulator →</button></section></div></div>;
}

function Prediction({ detail, prediction }) { if (!detail || !prediction) return <Empty text="Select a corridor to view prediction." />; return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">PROTOTYPE ML MODEL</p><h2>Future Risk Prediction</h2><p>{detail.road_name}</p></div><span className="model-badge">Random Forest severity proxy</span></div><div className="prediction-hero"><div><span>Current risk</span><strong>{prediction.current_risk}</strong></div><div className="arrow">→</div><div><span>Predicted risk</span><strong>{prediction.predicted_risk}</strong></div><RiskBadge level={prediction.predicted_level} score={prediction.predicted_risk} /></div><div className="overview-grid"><section className="panel"><p className="eyebrow">OUTLOOK</p><h3>{prediction.trend} trend</h3><p className="explanation">This is a prototype severity-proxy estimate. A normalized risk score is not an accident probability.</p><div className="trend-line">{(detail.trend || []).map((item) => <div key={item.year}><i style={{ height: `${Math.max(14, Math.min(100, item.accidents / 3))}%` }} /><span>{item.year}</span></div>)}</div></section><section className="panel"><p className="eyebrow">IMPORTANT FEATURES</p><h3>Model signals</h3><Bars items={(prediction.important_features || []).map((item) => ({ name: item.feature.replace('cat__', '').replace('remainder__', ''), value: item.importance * 100 }))} color="#c9f277" /></section></div><section className="panel metrics-panel"><p className="eyebrow">CALCULATED METRICS</p><div className="metric-list">{Object.entries(prediction.metrics || {}).filter(([key]) => ['mae', 'rmse', 'r2'].includes(key)).map(([key, value]) => <div key={key}><span>{key.toUpperCase()}</span><b>{value ?? '—'}</b></div>)}</div><small>Feature importance does not imply causality.</small></section></div>; }

function Interventions({ interventions, simulate }) { return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">INTERVENTION INTELLIGENCE</p><h2>Recommended interventions</h2><p>Ranked by supported factor matches, effectiveness, urgency, and feasibility.</p></div></div><div className="intervention-grid full">{interventions.map((item, index) => <article className="intervention-card" key={item.id}><div className="card-top"><span className="rank">#{index + 1}</span><span className="model-badge">{item.confidence}</span></div><h3>{item.name}</h3><p>{item.reason}</p><div className="match-list">{(item.matched_factors || []).map((factor) => <span key={factor}>{factor}</span>)}{!item.matched_factors?.length && <span>General safety audit</span>}</div><div className="card-stats"><div><b>{Math.round(item.effectiveness * 100)}%</b><small>estimated effect</small></div><div><b>{item.cost}</b><small>cost</small></div><div><b>{item.timeframe}</b><small>timeframe</small></div></div><button className="action" onClick={() => simulate([item.id])}>Simulate this →</button></article>)}</div></div>; }

function Simulator({ locations, selected, detail, interventions, simulation, run }) { const [chosen, setChosen] = useState([]); const toggle = (id) => setChosen((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">SCENARIO PLANNING</p><h2>What-if Simulator</h2><p>Compare intervention options using bounded scenario estimates.</p></div><select value={selected || ''} onChange={(event) => window.dispatchEvent(new CustomEvent('roadpulse-select', { detail: event.target.value }))}>{locations.map((item) => <option key={item.id} value={item.id}>{item.road_name}</option>)}</select></div>{detail && <div className="simulator-layout"><section className="panel scenario-controls"><p className="eyebrow">SELECT INTERVENTIONS</p><h3>Current risk <strong className="lime">{detail.risk.risk_score}</strong></h3>{interventions.map((item) => <label className="check-row" key={item.id}><input type="checkbox" checked={chosen.includes(item.id)} onChange={() => toggle(item.id)} /><span><b>{item.name}</b><small>{item.matched_factors?.join(' · ') || 'General safety audit'} · {item.cost}</small></span></label>)}<button className="action wide" disabled={!chosen.length} onClick={() => run(chosen)}>Run scenario →</button></section><section className="panel scenario-result"><p className="eyebrow">SCENARIO-BASED ESTIMATED IMPACT</p>{simulation ? <><div className="scenario-number"><strong>{simulation.current_risk}</strong><span>→</span><strong>{simulation.scenario_risk}</strong></div><h3>Estimated reduction: {simulation.estimated_reduction} points</h3><p>{simulation.estimated_reduction_percent}% estimated improvement · {simulation.label}</p><small>{simulation.disclaimer}</small></> : <div className="empty-inline">Choose one or more interventions and run the scenario.</div>}</section></div>}</div>; }

function ActionPlan({ plan }) { const download = () => { const headers = Object.keys(plan[0] || {}); const csv = [headers.join(','), ...plan.map((row) => headers.map((key) => JSON.stringify(row[key] ?? '')).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'roadpulse-action-plan.csv'; link.click(); }; return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">AUTHORITY PRIORITIZATION</p><h2>Priority Action Plan</h2><p>Ranked corridors for operational follow-through.</p></div><div><button className="action secondary" onClick={() => window.print()}>Print</button><button className="action" onClick={download}>Download CSV</button></div></div><section className="panel table-panel"><table><thead><tr><th>Priority</th><th>Road</th><th>District</th><th>Risk</th><th>Cause</th><th>Intervention</th><th>Cost</th><th>Urgency</th></tr></thead><tbody>{plan.map((item) => <tr key={item.priority}><td>#{item.priority}</td><td><b>{item.road_name || item.road}</b><small>{item.state}</small></td><td>{item.district}</td><td><RiskBadge level={item.risk_level} score={item.risk_score || item.current_risk} /></td><td>{item.main_cause || 'Road risk factors'}</td><td>{item.recommended_intervention}</td><td>{item.cost}</td><td><span className="urgency">{item.urgency}</span></td></tr>)}</tbody></table></section></div>; }

function UploadPage({ refresh, summary }) { const [file, setFile] = useState(null); const [preview, setPreview] = useState([]); const [message, setMessage] = useState(''); const choose = (event) => { const next = event.target.files[0]; setFile(next); if (next) next.text().then((text) => setPreview(text.split('\n').slice(0, 6).map((line) => line.split(',')))); }; const upload = () => file && uploadData(file).then((result) => { setMessage(`${result.total_records} rows processed as USER DATA`); refresh(); }).catch(() => setMessage('Upload failed. Check the CSV columns.')); return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">DATA OPERATIONS</p><h2>Upload accident data</h2><p>Recognized aliases are normalized by the backend before analytics refresh.</p></div><span className="model-badge">{summary?.data_label}</span></div><section className="panel upload-panel"><input type="file" accept=".csv" onChange={choose} /><p className="eyebrow">PREVIEW / FIRST 5 ROWS</p>{preview.length ? <div className="preview-table">{preview.map((row, index) => <div key={index}>{row.map((cell, cellIndex) => <span key={cellIndex}>{cell}</span>)}</div>)}</div> : <div className="empty-inline">Choose a CSV to preview it before processing.</div>}<button className="action" disabled={!file} onClick={upload}>Process and refresh analytics →</button>{message && <p className="upload-message">{message}</p>}</section></div>; }

function Model({ prediction, summary }) { return <div className="page-stack"><div className="page-title"><div><p className="eyebrow">TRANSPARENCY LAYER</p><h2>Model Insights</h2><p>Prototype metrics and feature signals from the current dataset.</p></div><span className="model-badge">Prototype ML Model</span></div><div className="kpis model-kpis"><div className="kpi"><span>DATASET ROWS</span><strong>{prediction?.metrics?.records ?? '—'}</strong></div><div className="kpi"><span>MODEL TYPE</span><strong>RF</strong></div><div className="kpi"><span>DATASET</span><strong>{summary?.data_label || '—'}</strong></div></div><section className="panel"><p className="eyebrow">IMPORTANT FEATURES</p><h3>What the model used</h3>{prediction ? <Bars items={(prediction.important_features || []).map((item) => ({ name: item.feature, value: item.importance * 100 }))} /> : <div className="empty-inline">Select a corridor to load feature importance.</div>}<p className="disclaimer">Feature importance does not imply causality. The normalized risk score is not an accident probability.</p></section></div>; }
function Empty({ text }) { return <div className="empty-page"><h3>{text}</h3><p>Choose a road from Risk Map to continue.</p></div>; }

function App() {
  const [page, setPage] = useState('overview'); const [summary, setSummary] = useState(null); const [locations, setLocations] = useState([]); const [selected, setSelected] = useState(null); const [detail, setDetail] = useState(null); const [prediction, setPrediction] = useState(null); const [interventions, setInterventions] = useState([]); const [plan, setPlan] = useState([]); const [health, setHealth] = useState(null); const [simulation, setSimulation] = useState(null); const [error, setError] = useState(''); const [search, setSearch] = useState('');
  const load = () => Promise.all([getHealth(), getDashboardSummary(), getLocations(), getActionPlan()]).then(([nextHealth, nextSummary, nextLocations, nextPlan]) => { setHealth(nextHealth); setSummary(nextSummary); setLocations(nextLocations); setPlan(nextPlan); setSelected((current) => current || nextLocations[0]?.id); }).catch((error) => setError(error.message || 'RoadPulse backend unavailable'));
  useEffect(() => { load(); const listener = (event) => setSelected(event.detail); window.addEventListener('roadpulse-select', listener); return () => window.removeEventListener('roadpulse-select', listener); }, []);
  useEffect(() => { if (!selected) return; Promise.all([getLocation(selected), getInterventions(selected), getPrediction(selected)]).then(([nextDetail, nextInterventions, nextPrediction]) => { setDetail(nextDetail); setInterventions(nextInterventions); setPrediction(nextPrediction); }).catch((error) => setError(error.message || 'RoadPulse backend unavailable')); }, [selected]);
  const selectRoad = (id, target = 'intelligence') => { setSelected(id); setPage(target); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const filteredSearch = search ? locations.filter((item) => `${item.road_name} ${item.state} ${item.district}`.toLowerCase().includes(search.toLowerCase())).slice(0, 5) : [];
  const run = (ids) => simulateInterventions(selected, ids).then(setSimulation).catch(() => setError('Unable to calculate scenario'));
  if (error) return <main className="app-error"><div><h2>{error}</h2><button className="action" onClick={() => { setError(''); load(); }}>Retry connection</button></div></main>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><h1>RoadPulse <span>AI</span></h1><p>Predict. Explain. Prevent. Prioritize.</p></div><nav>{pages.map(([id, label]) => <button className={page === id ? 'nav-item active' : 'nav-item'} key={id} onClick={() => setPage(id)}><span className={`nav-icon icon-${id}`} />{label}</button>)}</nav><div className="sidebar-foot"><i />{health?.status === 'ok' ? 'Backend connected' : 'Connecting'}<small>{summary?.data_label || 'LOADING DATA'}</small></div></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">ROAD SAFETY INTELLIGENCE / LIVE WORKSPACE</p><h2>{pages.find(([id]) => id === page)?.[1]}</h2></div><div className="global-search"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search road, district, state..." />{filteredSearch.length > 0 && <div className="search-results">{filteredSearch.map((item) => <button key={item.id} onClick={() => { setSearch(''); selectRoad(item.id); }}>{item.road_name}<small>{item.state} / {item.district}</small></button>)}</div>}</div></header>{page === 'overview' && <Overview summary={summary} locations={locations} open={selectRoad} />}{page === 'map' && <RiskMap locations={locations} select={setSelected} open={selectRoad} />}{page === 'intelligence' && <Intelligence detail={detail} prediction={prediction} openSimulator={() => setPage('simulator')} />}{page === 'prediction' && <Prediction detail={detail} prediction={prediction} />}{page === 'interventions' && <Interventions interventions={interventions} simulate={(ids) => { run(ids); setPage('simulator'); }} />}{page === 'simulator' && <Simulator locations={locations} selected={selected} detail={detail} interventions={interventions} simulation={simulation} run={run} />}{page === 'action' && <ActionPlan plan={plan} />}{page === 'upload' && <UploadPage summary={summary} refresh={load} />}{page === 'model' && <Model prediction={prediction} summary={summary} />}<footer className="app-footer">RoadPulse AI · Prototype planning tool · Scenario estimates are not causal guarantees</footer></main></div>;
}

createRoot(document.getElementById('root')).render(<App />);
